# Importando as bibliotecas

In [7]:
import pandas as pd
import warnings
from pyvis.network import Network
warnings.filterwarnings('ignore')

# Ajustando o √çndice

In [8]:
df = pd.read_csv("main_names.csv", sep = ';')

In [9]:
df['Indice'] = df['Unnamed: 0']
df = df.drop(columns='Unnamed: 0')
df

,Name,d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,Indice
0,"Bacon, Kevin",1.0,1181.0,71397.0,124975.0,25665.0,1787.0,196.0,22.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,"Jones, James Earl",1.0,1828.0,98183.0,110349.0,13823.0,926.0,96.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,"Irizarry, Vincent",1.0,58.0,14785.0,141165.0,62805.0,5886.0,479.0,41.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,"Bolger, John",1.0,79.0,16056.0,136632.0,66264.0,5682.0,438.0,63.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,"Newman, Robert",1.0,42.0,358.0,31830.0,159015.0,31479.0,2242.0,231.0,25.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225317,"Ceret, Domingo",1.0,5.0,3.0,5.0,3.0,9.0,1080.0,51463.0,147266.0,23257.0,1920.0,174.0,34.0,6.0,NaN,NaN,NaN,NaN,248238
225318,"Hidalgo, Consuelo",1.0,3.0,5.0,5.0,3.0,9.0,1080.0,51463.0,147266.0,23257.0,1920.0,174.0,34.0,6.0,NaN,NaN,NaN,NaN,248239
225319,"Jordi, Elena",1.0,3.0,5.0,5.0,3.0,9.0,1080.0,51463.0,147266.0,23257.0,1920.0,174.0,34.0,6.0,NaN,NaN,NaN,NaN,248240
225320,"Quintanilla, Hector",1.0,2.0,3.0,3.0,5.0,3.0,9.0,1080.0,51463.0,147266.0,23257.0,1920.0,174.0,34.0,6.0,NaN,NaN,NaN,248241
225321,"Alfonso, Josep",1.0,2.0,3.0,3.0,5.0,3.0,9.0,1080.0,51463.0,147266.0,23257.0,1920.0,174.0,34.0,6.0,NaN,NaN,NaN,248242

# Puxando uma base externa para fazer as rela√ß√µes de ganhadores do Oscar

In [10]:
oscar = pd.read_csv('oscar.csv')

In [12]:
nomes = []
indices = []
for i in df['Name']:
    p = df[df['Name'] == i]['Indice'].values
    if i in oscar[oscar['winner'] == True]['name'].unique():
        nomes.append(i)
        indices.append(p[0])

KeyboardInterrupt:

In [ ]:
for i in indices:
    nao_oscar.remove(i)

In [ ]:
nao_oscar

# Usando a base rela√ß√µes como aresta

In [ ]:
relations = pd.read_csv("relations.csv", sep = ';')
relations

In [ ]:
for i in nao_oscar:
    relations[0] = relations[relations[0] != i]
    relations[1] = relations[relations[1] != i]

In [ ]:
records = relations.to_records(index=False)
arestas = list(records)

In [ ]:
net = Network()
net.add_node(indices, label=nomes)
net.add_edges(arestas)
net.show('nodes.html')